// AUTO-GENERATED by tools/gen-sw.mjs — do not edit by hand.
const CACHE = 'lana-life-03db737f5b';
const ASSETS = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./css/fonts.css",
  "./css/style.css",
  "./js/art/character.js",
  "./js/art/hair.js",
  "./js/art/palette.js",
  "./js/art/pets.js",
  "./js/art/scenes/beach.js",
  "./js/art/scenes/cafe.js",
  "./js/art/scenes/college.js",
  "./js/art/scenes/common.js",
  "./js/art/scenes/dorm.js",
  "./js/art/scenes/garden.js",
  "./js/art/scenes/home.js",
  "./js/art/scenes/mall.js",
  "./js/art/scenes/park.js",
  "./js/audio.js",
  "./js/config.js",
  "./js/core/bus.js",
  "./js/core/progress.js",
  "./js/core/state.js",
  "./js/core/time.js",
  "./js/data/achievements.js",
  "./js/data/actions.js",
  "./js/data/contacts.js",
  "./js/data/items.js",
  "./js/data/places.js",
  "./js/data/quests.js",
  "./js/data/scenes.js",
  "./js/game.js",
  "./js/main.js",
  "./js/minigames/barista.js",
  "./js/minigames/catcher.js",
  "./js/minigames/crown.js",
  "./js/minigames/framework.js",
  "./js/minigames/index.js",
  "./js/minigames/mandarins.js",
  "./js/minigames/memory.js",
  "./js/minigames/petplay.js",
  "./js/minigames/runner.js",
  "./js/minigames/shells.js",
  "./js/pwa.js",
  "./js/ui/cutscenes.js",
  "./js/ui/dom.js",
  "./js/ui/fx.js",
  "./js/ui/hud.js",
  "./js/ui/menu.js",
  "./js/ui/modal.js",
  "./js/ui/phone.js",
  "./js/ui/wardrobe.js",
  "./js/ui/world.js",
  "./assets/fonts/marck-script-cyrillic-400-normal.woff2",
  "./assets/fonts/marck-script-latin-400-normal.woff2",
  "./assets/fonts/nunito-cyrillic-400-normal.woff2",
  "./assets/fonts/nunito-cyrillic-700-normal.woff2",
  "./assets/fonts/nunito-cyrillic-800-normal.woff2",
  "./assets/fonts/nunito-cyrillic-900-normal.woff2",
  "./assets/fonts/nunito-latin-400-normal.woff2",
  "./assets/fonts/nunito-latin-700-normal.woff2",
  "./assets/fonts/nunito-latin-800-normal.woff2",
  "./assets/fonts/nunito-latin-900-normal.woff2",
  "./icons/apple-touch-icon.png",
  "./icons/favicon-64.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(req)
          .then((res) => {
            if (res.ok) {
              const copy = res.clone();
              caches.open(CACHE).then((c) => c.put(req, copy));
            }
            return res;
          })
          .catch(() => caches.match('./index.html')),
    ),
  );
});
