const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
export default async ({ page, shot }) => {
  const tap = async (sel) => { await page.waitForSelector(sel, { timeout: 8000 }); await page.$eval(sel, (el) => el.click()); await sleep(450); };
  await page.goto('http://localhost:8080/index.html');
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await sleep(1500);
  await shot('40-title-desk');
  await tap('.title-actions .btn');
  await sleep(600);
  await shot('41-intro-desk');
  await tap('.story .skip');
  await sleep(2500);
  await shot('42-game-desk');
  await page.evaluate(() => { __lana.S.minutes = 22 * 60; });
  await sleep(1200);
  await shot('43-night-desk');
  await tap('.hotspot[data-id="bed"]');
  await tap('.action-menu .act');
  await sleep(2500);
  await shot('44-sleep');
  await sleep(5000);
  await shot('45-morning');
  await tap('.phone-btn');
  await sleep(600);
  await shot('46-phone-desk');
  await tap('[data-app="achievements"]');
  await shot('47-ach');
  await tap('.app-view .back');
  await tap('[data-app="profile"]');
  await shot('48-profile');
};
