// Generates sw.js with a precache list of every runtime asset + a content hash as cache version.
import { readdirSync, statSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';

const roots = ['index.html', 'manifest.webmanifest', 'css', 'js', 'assets', 'icons'];
const files = [];
const walk = (p) => {
  const st = statSync(p);
  if (st.isDirectory()) for (const f of readdirSync(p).sort()) walk(join(p, f));
  else if (!/\.(txt|md)$/.test(p)) files.push(p);
};
roots.forEach(walk);
const hash = createHash('sha1');
for (const f of files) hash.update(f).update(readFileSync(f));
const version = hash.digest('hex').slice(0, 10);
const list = ['./', ...files.map((f) => './' + f)];

const sw = `// AUTO-GENERATED by tools/gen-sw.mjs — do not edit by hand.
const CACHE = 'lana-life-${version}';
const ASSETS = ${JSON.stringify(list, null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(req)
          .then((res) => {
            if (res.ok) {
              const copy = res.clone();
              caches.open(CACHE).then((c) => c.put(req, copy));
            }
            return res;
          })
          .catch(() => caches.match('./index.html')),
    ),
  );
});
`;
writeFileSync('sw.js', sw);
console.log(`sw.js: ${list.length} files, version ${version}`);
